// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF4yctggEqVAMXmO8u5JRfCI3Ajq-Q5iw',
    appId: '1:558971666380:web:584d0770fa84519e5fa769',
    messagingSenderId: '558971666380',
    projectId: 'zync-70721',
    authDomain: 'zync-70721.firebaseapp.com',
    storageBucket: 'zync-70721.firebasestorage.app',
    measurementId: 'G-LL2DBRNGM4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb6fRMt9fM6RRfy7tyjyDvAu-Ujth2l2k',
    appId: '1:558971666380:android:be81e30dbd28a4f65fa769',
    messagingSenderId: '558971666380',
    projectId: 'zync-70721',
    storageBucket: 'zync-70721.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeWym5qmjB633dbdwXEhac7BtzM5QkugQ',
    appId: '1:558971666380:ios:3165245ee74ce4515fa769',
    messagingSenderId: '558971666380',
    projectId: 'zync-70721',
    storageBucket: 'zync-70721.firebasestorage.app',
    iosBundleId: 'com.example.zync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeWym5qmjB633dbdwXEhac7BtzM5QkugQ',
    appId: '1:558971666380:ios:3165245ee74ce4515fa769',
    messagingSenderId: '558971666380',
    projectId: 'zync-70721',
    storageBucket: 'zync-70721.firebasestorage.app',
    iosBundleId: 'com.example.zync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF4yctggEqVAMXmO8u5JRfCI3Ajq-Q5iw',
    appId: '1:558971666380:web:849972ef5717f4135fa769',
    messagingSenderId: '558971666380',
    projectId: 'zync-70721',
    authDomain: 'zync-70721.firebaseapp.com',
    storageBucket: 'zync-70721.firebasestorage.app',
    measurementId: 'G-1ZV29VTD16',
  );
}
